let lesson = [
    {
        "id": 1,
        "title": "Math",
        "location": "London",
        "price": 100,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 2,
        "title": "Science",
        "location": "London",
        "price": 90,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 3,
        "title": "Music",
        "location": "London",
        "price": 110,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 4,
        "title": "Geology",
        "location": "Glassglow",
        "price": 120,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 5,
        "title": "Histroy",
        "location": "Sutton",
        "price": 150,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 6,
        "title": "Biology",
        "location": "Wales",
        "price": 80,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 7,
        "title": "Karate",
        "location": "Reading",
        "price": 70,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 8,
        "title": "English",
        "location": "Oxford",
        "price": 100,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 9,
        "title": "Computing",
        "location": "Cardif",
        "price": 160,
        "space": 5,
        "image": "math.png",
    },
    {
        "id": 10,
        "title": "Automation",
        "location": "Birstol",
        "price": 190,
        "space": 5,
        "image": "math.png",
    },
]